title: C-lasso
description: "The replication data and files for Liangjun Su, Zhentao Shi and Peter Phillips (2015): “Identifying Latent Structures in Panel Data”"
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
